[package]
name = "day16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.12"
derive-new = "0.5.9"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
rayon = "1.6.1"
regex = "1.7.0"